export const TIME_LOADED = "TIME_LOADED"; // Used by test reducer
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";
export const DISPLAY_MODAL = "DISPLAY_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const CREATE_SUCCESS = "CREATE_SUCCESS";
export const CREATE_ERROR = "CREATE_ERROR";
export const CLEAR_PRODUCTS = "CLEAR_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
